#include<stdio.h>
#include<stdlib.h>
#include<math.h>
#include<fftw3.h>
#define N 128
int main (void)
{


 FILE *fpt, *fpw;
 int i, j, t1, t2, tempr, tempg, templ;
 fftw_complex *comp_b, *comp_c;
 double comp_a[N][N];
 double tempa, tempb, tempc;
 int temp1,temp2,temp3;
 char fn1[100], fn2[100];
 int count;
 int initial;
 int final;
 int steps;

 comp_b = fftw_malloc (sizeof (fftw_complex) * N * N);
 comp_c = fftw_malloc (sizeof (fftw_complex) * N * N);
 printf ("Initial count \n");
 scanf ("%d", &initial);
 printf ("Final count \n");
 scanf ("%d", &final);
 printf ("Steps \n");
 scanf ("%d", &steps);
 for (count = initial; count <= final; count = count + steps) {
  sprintf (fn1, "comp.%06d", count);
  sprintf (fn2, "comp%06dcolor.eps", count);

  fpt = fopen (fn1, "r");

  fread (&comp_b[0][0], sizeof(double), 2 * N * N, fpt);
  fread (&comp_c[0][0], sizeof(double), 2 * N * N, fpt);

  fclose (fpt);

  for (i = 0; i < N; i++) {
   for (j = 0; j < N; j++) {
    comp_a[i][j] = 1.0 - comp_b[j + i * N][0] - comp_c[j + i * N][0];
   }
  }
  fpw = fopen (fn2, "w");
  fprintf (fpw, "%%!PS-Adobe-2.0 EPSF-2.0\n");
  fprintf (fpw, "%%%%Generated by C-Program output\n");
  fprintf (fpw, "%%%%Creator: Saswata\n");
  fprintf (fpw, "%%%%Title: Single Precipitate\n");
  fprintf (fpw, "%%%%BoundingBox: 0 0 %d %d\n", N/2, N/2);
  fprintf (fpw, "0  0 translate\n");
  fprintf (fpw, "0 rotate\n");
  fprintf (fpw, "%d %d scale\n", N/2, N/2);
  fprintf (fpw, "/picstr %d string def\n", N);
  fprintf (fpw, "%d %d 8 [%d 0 0 -%d 0 %d]\n", N, N, N, N, N);
  fprintf (fpw, "{currentfile picstr readhexstring pop}\n");
  fprintf (fpw, "false 3 colorimage\n");

  for (i = 0; i < N; i++) {
   for (j = 0; j < N; j++) {
    tempb = comp_b[j + i * N][0];
    tempc = comp_c[j + i * N][0];
    tempa = comp_a[i][j];
    if (tempa > 1.0)
     tempa = floor(tempa);
    if (tempb > 1.0)
     tempb = floor(tempb);
    if (tempc > 1.0)
     tempc = floor(tempc);
    if (tempa < 0.0)
     tempa = ceil(tempa);
    if (tempb < 0.0)
     tempb = ceil(tempb);
    if (tempc < 0.0)
     tempc = ceil(tempc);
     temp1=(int)255*tempa;
     temp2=(int)255*tempb;
     temp3=(int)255*tempc; 


    fprintf (fpw, "%02x%02x%02x", temp1,temp2,temp3);
   }
   fprintf (fpw, "\n");
  }

  fprintf (fpw, "grestore\n");
  fprintf (fpw, "showpage\n");
  fprintf (fpw, "%%%%EOF\n");
  fclose (fpw);
 }
 system ("mkdir EPS");
 system ("mv *.eps EPS/");
 fftw_free (comp_b);
 fftw_free (comp_c);

}
